// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(ReservationContext))]
    [Migration("20200814144659_Init2")]
    partial class Init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainLibrary.Client", b =>
                {
                    b.Property<int>("ClientNumber")
                        .HasColumnType("int");

                    b.Property<string>("ClientCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientNumber")
                        .HasName("PrimaryKey_ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DomainLibrary.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("DomainLibrary.Models.Price", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Arrangement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PriceRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PriceId");

                    b.HasIndex("CarId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("DomainLibrary.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReservationInfoId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientNumber");

                    b.HasIndex("ReservationInfoId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("DomainLibrary.Models.ReservationInfo", b =>
                {
                    b.Property<int>("ReservationInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Arrangement")
                        .HasColumnType("int");

                    b.Property<int>("EndHour")
                        .HasColumnType("int");

                    b.Property<int>("EndLocation")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StartHour")
                        .HasColumnType("int");

                    b.Property<int>("StartLocation")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ReservationInfoId");

                    b.ToTable("ReservationInfo");
                });

            modelBuilder.Entity("DomainLibrary.Client", b =>
                {
                    b.OwnsOne("DomainLibrary.Address", "Address", b1 =>
                        {
                            b1.Property<int>("ClientNumber")
                                .HasColumnType("int");

                            b1.Property<int>("AddressId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("HouseNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Streetname")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClientNumber");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("ClientNumber");
                        });
                });

            modelBuilder.Entity("DomainLibrary.Models.Price", b =>
                {
                    b.HasOne("DomainLibrary.Models.Car", null)
                        .WithMany("Price")
                        .HasForeignKey("CarId");
                });

            modelBuilder.Entity("DomainLibrary.Models.Reservation", b =>
                {
                    b.HasOne("DomainLibrary.Models.Car", "Car")
                        .WithMany("ReservationDetails")
                        .HasForeignKey("CarId");

                    b.HasOne("DomainLibrary.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientNumber");

                    b.HasOne("DomainLibrary.Models.ReservationInfo", "ReservationInfo")
                        .WithMany()
                        .HasForeignKey("ReservationInfoId");
                });

            modelBuilder.Entity("DomainLibrary.Models.ReservationInfo", b =>
                {
                    b.OwnsOne("DomainLibrary.DeliveryAddress", "Address", b1 =>
                        {
                            b1.Property<int>("ReservationInfoId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("AddressId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("HouseNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Streetname")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ReservationInfoId");

                            b1.ToTable("ReservationInfo");

                            b1.WithOwner()
                                .HasForeignKey("ReservationInfoId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
