//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFLayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFLayer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Reservation.
        /// </summary>
        public static string AddReservation {
            get {
                return ResourceManager.GetString("AddReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangement:.
        /// </summary>
        public static string Arrangement {
            get {
                return ResourceManager.GetString("Arrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limousine:.
        /// </summary>
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client:.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Overview.
        /// </summary>
        public static string CreateOverview {
            get {
                return ResourceManager.GetString("CreateOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Day:.
        /// </summary>
        public static string EndDay {
            get {
                return ResourceManager.GetString("EndDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Hour:.
        /// </summary>
        public static string EndHour {
            get {
                return ResourceManager.GetString("EndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N°:.
        /// </summary>
        public static string HouseNumber {
            get {
                return ResourceManager.GetString("HouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Arrival:.
        /// </summary>
        public static string LocationEnd {
            get {
                return ResourceManager.GetString("LocationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Departure:.
        /// </summary>
        public static string LocationStart {
            get {
                return ResourceManager.GetString("LocationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Reservation.
        /// </summary>
        public static string LookUpReservation {
            get {
                return ResourceManager.GetString("LookUpReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Day:.
        /// </summary>
        public static string StartDay {
            get {
                return ResourceManager.GetString("StartDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Hour:.
        /// </summary>
        public static string StartHour {
            get {
                return ResourceManager.GetString("StartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vip Services Rudy 2020.
        /// </summary>
        public static string StatusBarText {
            get {
                return ResourceManager.GetString("StatusBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street:.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string string1 {
            get {
                return ResourceManager.GetString("string1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom:.
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
